const alumni = {
    members: [
        {
            name: 'Emily Grace Kirkwood',
            title: 'President 2023-24',
            major: 'General Engineering \'24',
            year: 2024,
            // currentJob: '',
            avatar: '/assets/images/team/emily-grace.jpeg',
            linkedin: 'https://www.linkedin.com/in/johndoe',
            github: 'placeholder',
        },
        {
            name: 'Daniel Shenkelman',
            title: '',
            major: 'Mechanical Engineering \'24',
            year: 2024,
            // currentJob: '',
            // avatar: '/assets/images/team/emily-grace.jpeg',
            linkedin: 'https://www.linkedin.com/in/johndoe',
            github: 'placeholder',
        },
        {
            name: 'Max Daud',
            title: 'President 2021-22',
            major: 'Mechanical Engineering \'22',
            year: 2022,
            // currentJob: '',
            // avatar: '/assets/images/team/emily-grace.jpeg',
            linkedin: 'https://www.linkedin.com/in/johndoe',
            github: 'placeholder',
        },
        {
            name: 'Katie Bomhoff',
            title: '',
            major: 'Mechanical Engineering \'23',
            year: 2023,
            // currentJob: '',
            // avatar: '/assets/images/team/emily-grace.jpeg',
            linkedin: 'https://www.linkedin.com/in/johndoe',
            github: 'placeholder',
        },
        {
            name: 'Alan Huang',
            title: '',
            major: 'Mechanical Engineering \'22',
            year: 2022,
            // currentJob: '',
            // avatar: '/assets/images/team/emily-grace.jpeg',
            linkedin: 'https://www.linkedin.com/in/johndoe',
            github: 'placeholder',
        },
        {
            name: 'Zach Souders',
            title: '',
            major: 'Mechanical Engineering \'22',
            year: 2022,
            // currentJob: '',
            // avatar: '/assets/images/team/emily-grace.jpeg',
            linkedin: 'https://www.linkedin.com/in/johndoe',
            github: 'placeholder',
        },
    ]
}

export default alumni;