const team = {
  members: [
    {
      name: 'Niti Sinha',
      title: 'President',
      major: "Mechanical Engineering '27",
      year: '2027',
      // currentJob: '',
      avatar: '/assets/images/team/niti.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Jommy Fasehun',
      title: 'Treasurer',
      major: "Neuroscience '27",
      year: '2027',
      // currentJob: '',
      avatar: '/assets/images/team/jommy.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Han Zheng',
      title: 'Chief Engineer',
      major: "Mechanical Engineering '26",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/han.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Serzed Ampanas',
      title: 'Avionics Lead',
      major: "Chemical and Biomolecular Engineering '26",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/serzed.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Huy Lam',
      title: 'Secretary',
      major: "Molecular/Cellular Biology and Political Science '28",
      year: '2028',
      // currentJob: '',
      avatar: '/assets/images/team/huy.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Ava Sommer',
      title: 'Events Coordinator',
      major: "Computer Science and Applied Mathematics '28",
      year: '2028',
      // currentJob: '',
      avatar: '/assets/images/team/ava.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Trevor Black',
      title: 'Officer',
      major: "Computer Science '26",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/trevor.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Koji Shukawa',
      title: 'Officer',
      major: "Physics PhD '28",
      year: '2028',
      // currentJob: '',
      avatar: '/assets/images/team/koji.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Kai Ko',
      title: 'Officer',
      major: "Computer Science '24/'24.5",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/kai.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
  ],
};

export default team;
