const team = {
  members: [
    {
      name: 'Trevor Black',
      title: 'President',
      major: "Computer Science '26",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/trevor.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Jommy Fasehun',
      title: 'President',
      major: "Neuroscience '27",
      year: '2027',
      // currentJob: '',
      avatar: '/assets/images/team/jommy.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Serzed Ampanas',
      title: 'Treasurer',
      major: "Chemical and Biomolecular Engineering '26",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/serzed.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Koji Shukawa',
      title: 'Officer',
      major: "Physics PhD '28",
      year: '2028',
      // currentJob: '',
      avatar: '/assets/images/team/koji.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
    {
      name: 'Kai Ko',
      title: 'Officer',
      major: "Computer Science '24/'24.5",
      year: '2026',
      // currentJob: '',
      avatar: '/assets/images/team/kai.jpg',
      linkedin: 'https://www.linkedin.com/in/johndoe',
      github: 'placeholder',
    },
  ],
};

export default team;
