site:
  name: JHU DBF
  site: 'https://jhu-dbf-website.pages.dev/'
  base: '/' # Change this if you need to deploy to Github Pages, for example
  trailingSlash: false

  googleSiteVerificationId: false

metadata:
  title:
    default: JHU DBF
    template: '%s — JHU DBF'
  description: "U/00002708 The official website for Design Build Fly at Johns Hopkins"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: JHU DBF
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
